albergue/albergue/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path("rosetta", include('rosetta.urls')),
    re_path("", include('applications.users.urls')),
    re_path("", include('applications.home.urls')),
    re_path("", include('applications.reservas.urls')),
    
]
# urlpatterns+=i18n_patterns(
#     path("rosetta", include('rosetta.urls')),
#     re_path("", include('applications.users.urls')),
#     re_path("", include('applications.home.urls')),
# )

albergue/applications/reservas/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name='reservas_app'

urlpatterns = [
    path("listar_reservas/", login_required(views.listar), name='listar_reservas'),
    path("prueba/", login_required(views.prueba), name='prueba'),
    path("all_events/", login_required(views.all_events), name='all_events'),
    path("registro_reservas/", login_required(views.ReservaRegisterView.as_view()), name='registro_reservas'),
    
]

albergue/applications/users/urls.py
from django.urls import path

from . import views

app_name='users_app'

urlpatterns = [
    path("registro/", views.UserRegisterView.as_view(), name='registro'),
    path("login/", views.Login.as_view(), name='login'),
    path("logout/", views.Logout.as_view(), name='logout'),
    path("update/", views.UpdatePasswordView.as_view(), name='update'),
    
]

albergue/templates/base.html
{% load static %} {% load i18n %}
<!DOCTYPE html>
<html lang="{{ lang.0 }}">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static 'css/select_languages.css' %}" rel="stylesheet">
    <link href="{% static 'css/style_header.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.css" /> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/locale-all.js"></script>

    <!-- <script src="{% static 'fullcalendar/lib/jquery.min.js' %}"></script> -->
    <link rel="stylesheet" href="{% static 'css/fullcalendar.css' %}" />
    <!-- <script src="{% static 'fullcalendar/lib/moment.min.js' %}"></script> -->
    <!-- <script src="{% static 'fullcalendar/locale-all.js' %}"></script> -->
    <!-- <script src="{% static 'fullcalendar/fullcalendar.js' %}"></script> -->
    <title>{% block title %} {% endblock title %}</title>
    {% block extra_css %}{% endblock extra_css%}
</head>


<body>

    <div class="header">
        <div class="rayitas">
            <img id="menu" src="{% static 'imagenes/icons8-menú-redondeado-96.png' %}" alt="show menu">
        </div>
        <h1>{% trans 'Inicio' %}</h1>
        <h2> {% trans 'Bienvenido' %} {{user}}</h2>
        <fieldset>
            <legend>{% trans 'Cambiar idioma' %}</legend>

            <form action="/i18n/setlang/" method="post">

                {% csrf_token %}
                <div style="display:inline;"></div>
                <select name="language" onchange="javascript:form.submit()">
                {% for lang in LANGUAGES %}
                <option value="{{ lang.0 }}" {% if LANGUAGE_CODE %} selected="selected" {% endif %}>
                    {{ lang.1}}
                </option>
                {% endfor %}
            </select>
            </form>
        </fieldset>

    </div>

    <div id="nav" class="active">
        <ul>
            <li>
                <a href="{% url 'users_app:logout' %}">{% trans 'Cerrar sesión' %}</a></li>
            <li>
                <a href="{% url 'users_app:login' %}">{% trans 'Login' %}</a>
            </li>
            <li>
                <a href="{% url 'users_app:registro' %}">{% trans 'Registro' %}</a>
            </li>
            <li>
                <a href="{% url 'reservas_app:listar_reservas' %}">{% trans 'Mostrar disponbilidad' %}</a>
            </li>
            {% if request.user.is_authenticated %}
            <li>
                <a href="{% url 'users_app:update' %}">{% trans 'Cambiar contraseña' %}</a>
            </li>
            <li>
                <a href="{% url 'reservas_app:registro_reservas' %}">{% trans 'Registrar reserva' %}</a>
            </li>
            {% endif %}
        </ul>
    </div>
    <h1>{% trans 'Prueba español' %}</h1>

    <div id="main">
        {% block contenido %} {% endblock contenido %}


    </div>
    <script src="{% static 'js/select_languages.js' %}"></script>


    {% block extra_js %}{% endblock extra_js %}

    <script src="{% static 'js/menu.js' %}"></script>
</body>

</html>